### PR TITLE
Fix file names with CS extension instead of cs

### PR DESCRIPTION
**Pull request by coderpatros**
This should fix the issue reported here https://github.com/actions/setup-dotnet/issues/37

Linux filesystems are interesting beasts. And you hit a case sensitivity issue.

Out of the box the solution would not compile for me at all on linux. It still doesn't because of the full framework project. But I can now build the `OpenProtocolInterpreter.csproj` project without issue.

### CODE REVIEW

**Comment by Rickedb** [comment]
No way it was filename issue! Visual Studio 2019 sometimes renames my extensions to .CS! 

Going to make tests at night. Thank you for helping!

**Comment by coderpatros** [comment]
Ha ha, yeah. It had me stumped for a while.

It basically went like this...
What the **** do you mean the "type or namespace" can't be found. I can see it right here in this file. Which looks exactly like all the other damn files. Flick back and forth between a few of the files for a while comparing. Well I don't think the issue is with those files, might open another one. Go to my file explorer... oh :facepalm:

**Comment by Rickedb** [comment]
I had this type of problem some months ago when using docker in another projects. Never thought it could be the case here!

**Comment by Abdul-Wahab-Khan** [comment]
Thanks Brothers, I had the same issue in ubuntu, and did everything but couldn't solve it until I saw issue.
Thanks a lot

**Pull request merged**
