### PR TITLE
MID0150 create correct package depending on size of identifier

### PR DESCRIPTION
**Pull request by xGusu**
For me  default solution didnt work with a Dessoutter Controller so i had to adjust the package .
Also i modify the the tests.
If you think is ok please add it .

### CODE REVIEW

**Comment by Rickedb** [comment]
Does it applies only to Dessoutter Tightening controllers or is it for everyone?
If it's only for Dessoutter, I might break other communications.

**Comment by xGusu** [comment]
if you have a look in your provided example for test "00470150001         My identifier less than 100"
the package had length 47 but if you create you the mid with the current mid you get maximum length all the time.
Maybe was an error when you construct the package with full size message . 
Identifier data 21-max 120 Max 100 ASCII characters
Could be also a bug in documentation when you send max length message .
My approach actually follow the protocol rule to calculate the correct size of the package every time so should not be any problem with other controllers.

**Comment by xGusu** [comment]
Desoutter controllers are based on atlas copco open protocol docu. They just add some additional mids.
If you need i will add the document to the docu section

**Comment by Rickedb** [comment]
@xGusu, just reviewed here, it's fine! 
I would just ask a favor, please add the documentation into docs folder, maybe it could help other people too, since the documentations are usually rare to find (even AtlasCopco).

**Comment by Rickedb** [comment]
@xGusu, thank you for contributing, I'm going to create a release when possible.

**Pull request merged**
